use_frameworks!

target 'HXDropMenu_Example' do
  pod 'HXDropMenu', :path => '/Users/haixiao/Desktop/OCDevelopment/HXDropMenu'
  pod 'HXTool'
  target 'HXDropMenu_Tests' do
    inherit! :search_paths

    
  end
end
